[package]
name = "ptcgp-db-data"
version = "0.5.0"
edition = "2024"
license.workspace = true
build = "codegen/main.rs"

[lints]
workspace = true

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
gcd = "2"
memchr = "2"
smallvec = "1"
smol_str = "0.3"

[build-dependencies]
anyhow = "1"
chrono = { version = "0.4", features = ["serde"] }
gcd = "2"
prettyplease = "0.3"
proc-macro2 = { version = "1", default-features = false }
quote = { version = "1", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }
syn = { version = "3", default-features = false, features = ["parsing"] }
icu_normalizer = { version = "2", features = ["compiled_data"] }

