[application]
name = "ptcgp-db"
default_platform = "web"

[web.app]
title = "PTCGP DB"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []
