[application]
name = "ptcgp-db"
default_platform = "web"
tailwind_input = "tailwind.css"
tailwind_output = "public/tailwind.css"

[web.app]
title = "PTCGP DB"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource]
style = ["tailwind.css"]
script = []

[web.resource.dev]
style = []
script = []
